services:
  pulse:
    build: build/pulse
    restart: unless-stopped
    volumes:
      - ./pulse:/run/pulse

  ledfx:
    build: build/ledfx
    restart: unless-stopped
    depends_on:
      - pulse
    ports:
      - 8888:8888
    volumes:
      - ./ledfx-config:/root/.ledfx
      - ./pulse:/run/pulse

  shairport-sync:
    image: mikebrady/shairport-sync
    restart: unless-stopped
    depends_on:
      - pulse
    environment:
      - PULSE_SERVER=unix:/run/pulse/native
    network_mode: host
    volumes:
      - ./pulse:/run/pulse
    entrypoint: /init /command/with-contenv /run.sh
    command: --verbose --output=pa
