---

name: Build Base
on:
  push:
    tags-ignore:
      - '**'
    branches:
      - '**'
  workflow_dispatch:
  repository_dispatch:
    types: [base]

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dockerfile:
          - pulse
          - ledfx
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: $-buildx-base-$
          restore-keys: |
            $-buildx-base-

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Get Time
        id: time
        uses: nanzm/get-time-action@v2.0
        with:
          format: 'MMDDHHmm'

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build
        uses: docker/build-push-action@v5
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./docker/${{ matrix.dockerfile }}
          file: ./docker/${{ matrix.dockerfile }}/Dockerfile
          push: true
          tags: |
            unixology/${{ matrix.dockerfile }}:latest
            unixology/${{ matrix.dockerfile }}:${{ steps.time.outputs.time }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max
